### ISSUE TITLE
Unable to verify location of [convert,gs,ffmpeg,exiftool,AntiWord,pdftotext]

### ISSUE THREAD

**Issue by dnk8n** [suntorytimed/resourcespace-docker#1]
Upon initial install:

![screencapture-dam-vnet-lan-pages-setup-php-2021-02-11-14_06_30](https://user-images.githubusercontent.com/3307753/107634569-66b2d680-6c72-11eb-90c8-18e270b025a2.png)

How are these textboxes validated?

**Comment by suntorytimed** [comment]
Which version of the container did you pull for this? As far as I know this checks the default path of the required tools to run ResourceSpace. In case those diverge they need to be adjusted, but I am not aware that anything has change on Ubunut 18.04 base.

**Comment by dnk8n** [comment]
Seems to work without setting them at all. But if I manually set them it
fails as shown in the image.

**Comment by suntorytimed** [comment]
Ah, yes. I have checked it just now on the dev container. It looks like ResourceSpace just requires a path to the root of the binaries. Autodetect should set them to /usr/bin. As this is a ResourceSpace specific behaviour and not related to the container I would close this issue.
