### ISSUE TITLE
QNAP TS-251A container install

### ISSUE THREAD

**Issue by carlosalosno** [suntorytimed/resourcespace-docker#2]
Hi there, im pretty sure im so newbie with thso containers, but wuen i install yoru conatiner in Container station of a Qnap, guess miss mariadb service so i reach to the resourcespace config page but cant connect with database

any help?

**Comment by suntorytimed** [comment]
The container itself doesn't come with a database. It only provides Resourcespace. You can either connect it to an already existing mysql or mariaDB database provided by your NAS or deploy a mariaDB container. In the docker-compose example you can see a setup utilising this ResourceSpace container and a separate mariaDB container that is connected by putting in "mariadb" as the URL for the database in the initial configuration.
